---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: infrastructure

