apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      version: "1.24.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Explicitly set image to avoid "auto" resolution issues
    image:
      repository: docker.io/istio/proxyv2
      tag: 1.24.6
    service:
      type: LoadBalancer
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

