apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 30m
  chart:
    spec:
      chart: jenkins
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controller:
      componentName: "jenkins-controller"
      image:
        registry: "docker.io"
        repository: "jenkins/jenkins"
        tag: "lts-jdk17"
      
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      
      admin:
        username: "admin"
        password: "admin123"
      
      serviceType: ClusterIP
      servicePort: 8080
      
      installPlugins:
        - kubernetes:latest
        - workflow-aggregator:latest
        - git:latest
        - configuration-as-code:latest
        - sonar:latest
        - pipeline-stage-view:latest
        - blueocean:latest
        - docker-workflow:latest
        - pipeline-utility-steps:latest
        - credentials-binding:latest
        - github:latest
        - github-branch-source:latest
      
      JCasC:
        defaultConfig: true
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: "DevSecOps Pipeline - Spring PetClinic Microservices"
          security-config: |
            security:
              globalJobDslSecurityConfiguration:
                useScriptSecurity: false
    
    persistence:
      enabled: true
      size: 20Gi
    
    agent:
      enabled: true
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      podTemplates:
        maven: |
          - name: maven
            label: maven
            serviceAccount: jenkins
            containers:
              - name: maven
                image: maven:3.9-eclipse-temurin-17
                command: "/bin/sh -c"
                args: "cat"
                ttyEnabled: true
                resourceRequestCpu: "200m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "1000m"
                resourceLimitMemory: "1Gi"
        docker: |
          - name: docker
            label: docker
            serviceAccount: jenkins
            containers:
              - name: docker
                image: docker:24-dind
                command: "/bin/sh -c"
                args: "cat"
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "200m"
                resourceRequestMemory: "256Mi"

