apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 30m
  chart:
    spec:
      chart: jenkins
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
    timeout: 20m
  upgrade:
    remediation:
      retries: 3
    timeout: 20m
  values:
    controller:
      componentName: "jenkins-controller"
      image:
        registry: "docker.io"
        repository: "jenkins/jenkins"
        tag: "lts-jdk17"
      
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      
      admin:
        username: "admin"
        password: "admin123"
      
      serviceType: ClusterIP
      servicePort: 8080
      
      # Minimal plugins for faster startup
      installPlugins:
        - kubernetes:latest
        - workflow-aggregator:latest
        - git:latest
        - credentials-binding:latest
      
      # Increase startup probe timeout
      probes:
        startupProbe:
          failureThreshold: 30
          periodSeconds: 20
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 30
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
      
      # Disable JCasC for now to avoid boot failures
      JCasC:
        defaultConfig: false
    
    persistence:
      enabled: true
      size: 20Gi
    
    agent:
      enabled: true
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
