---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: cloudflare_api_token
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    # Domain filter - update with your domain
    domainFilters: []
    # Cloudflare specific settings
    extraArgs:
      - --cloudflare-proxied=false
      - --cloudflare-dns-records-per-page=100
    policy: sync
    registry: txt
    txtOwnerId: external-dns
    txtPrefix: "_externaldns."
    # Log level
    logLevel: info
    # RBAC
    rbac:
      create: true
    serviceAccount:
      create: true
      name: external-dns

