apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 30m
  chart:
    spec:
      chart: sonarqube
      version: "10.x"
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    deploymentType: StatefulSet
    replicaCount: 1
    
    resources:
      requests:
        cpu: 400m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    
    persistence:
      enabled: true
      size: 10Gi
    
    postgresql:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      persistence:
        enabled: true
        size: 10Gi
    
    service:
      type: ClusterIP
      externalPort: 9000
    
    ingress:
      enabled: false
    
    account:
      adminPassword: admin123
      currentAdminPassword: admin

