---
# Enable STRICT mTLS for the entire mesh
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
# Enable STRICT mTLS specifically for petclinic namespace
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: petclinic-mtls
  namespace: petclinic
spec:
  mtls:
    mode: STRICT
---
# DestinationRule to enforce mTLS for all services in petclinic
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: petclinic-mtls
  namespace: petclinic
spec:
  host: "*.petclinic.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

